/*
 * Java bean class for entity "charsets" 
 * Created on 2019-09-27 ( Date ISO 2019-09-27 - Time 13:04:43 )
 * Generated by Telosys Tools Generator ( version 3.1.0 )
 */

package ch.zhaw.iwi.zotero2excel.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * Java bean for entity "charsets"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
public class Charsets implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    private Integer    charsetID    ; // Id or Primary Key

    private String     charset      ;

    /**
     * Default constructor
     */
    public Charsets() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "charsetID" field value
     * This field is mapped on the database column "charsetID" ( type "INTEGER", NotNull : false ) 
     * @param charsetID
     */
	public void setCharsetID( Integer charsetID ) {
        this.charsetID = charsetID ;
    }
    /**
     * Get the "charsetID" field value
     * This field is mapped on the database column "charsetID" ( type "INTEGER", NotNull : false ) 
     * @return the field value
     */
	public Integer getCharsetID() {
        return this.charsetID;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "charset" field value
     * This field is mapped on the database column "charset" ( type "TEXT", NotNull : false ) 
     * @param charset
     */
    public void setCharset( String charset ) {
        this.charset = charset;
    }
    /**
     * Get the "charset" field value
     * This field is mapped on the database column "charset" ( type "TEXT", NotNull : false ) 
     * @return the field value
     */
    public String getCharset() {
        return this.charset;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(charsetID);
        sb.append("|");
        sb.append(charset);
        return sb.toString(); 
    } 

}
